[pytest]
env =
    KISPY_ACCOUNT_NO=8125211301-01
    KISPY_APP_KEY=PSY5XhtRsKHLNU0BQEgDZq9qkwLqFsRorBur
    KISPY_APP_SECRET=IUOdyycRgnsfG67uJUyxoCWn/g+zqtPHXIn9UEk8aHGnMvGQvJPHTZ0KclEfDjGdBJnPVAzDnPnl81ASHnkCuEaRS38ulOxds+3Vd5SHcEDPpe6SRds5dYiEXZcPXz2s4sGC7E1onEXwjIqLJO3FngxinxmGgzNFoAZZR6coiywnZVvpN0I=